apiVersion: v1
kind: Pod
metadata:
  name: gen-long-job${JOB_SUFFIX}
  namespace: vlad-dev
spec:
  containers:
    - name: data-generator
      image: python:3.12-slim
      command: ["/bin/bash", "-c"]
      args:
        - |
          apt-get update && \
          apt-get install -y git && \
          pip install polars pyarrow numpy 'cloudpathlib[s3]' python-dotenv boto3 && \
          git clone https://github.com/MultiQC/evals.git && \
          cd evals && \
          echo "Verifying AWS configuration..." && \
          python scripts/gen-long.py --num-runs ${TOTAL_RUNS} --workers 4 --start-from ${START_FROM} --end-at ${END_AT}
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SESSION_TOKEN
        - name: AWS_REGION
          value: "eu-west-2"
      resources:
        requests:
          memory: "8Gi"
          cpu: "4"
        limits:
          memory: "32Gi"
          cpu: "16"
  restartPolicy: Never
